### ISSUE TITLE
Extraction not working in combination with ExtractTextWebpackPlugin({allChunks: true})

### ISSUE THREAD

**Issue by thasmo** [kisenka/svg-sprite-loader#104]
Unfortunately I'm not able to extract referenced SVG files into a SVG sprite file.

The generated CSS looks like this ...
```css
background-image:url(undefined)
```
... and there is no SVG file created.

The rule for extraction looks like this:
```js
{
	test: /\.svg$/,
	loader: 'svg-sprite-loader',
	options: {
		extract: true
	}
}
```
And I've also added the plugin:
```js
import * as SpritePlugin from 'svg-sprite-loader/plugin.js';
// ...
plugins: [
	new SpritePlugin()
]
```
Any idea what could cause this? Is there anything I can provide so we can figure out together what is wrong? Thanks a lot for your work on this loader and your feedback!

**Comment by kisenka** [comment]
The fastest way is to create a repo with your setup. Also I need info about your env - nodejs version,   webpack version, OS.

**Comment by thasmo** [comment]
@kisenka I've pushed my current project's state to [thasmo/packman](https://github.com/thasmo/packman). Run `yarn install` or `npm install` to install it and `yarn run build:production` or `npm run build:production` to get a production build.

Fingers crossed it will run properly on your machine, it's still a proof of concept and only tested on:
* Windows 10 64-bit (Creators Update)
* Node 7.9.0
* Webpack 2.5.0
* Yarn 0.24.1

This is not a simplified test-case but I hope you can reproduce the problem - otherwise I can try to build a test-case whenever I have the time.

**Comment by thasmo** [comment]
Relevant configuration for spriting is in `/.packman/packs/extraction-vector-sprite.ts`.

**Comment by thasmo** [comment]
Feel free to just ask if I can provide anything else.

**Comment by kisenka** [comment]
I found 2 issues:
1. If you import SVGs from CSS/SCSS/etc - extract option should be `true`, because in this mode loader return sprite URL with symbol id, e.g. `sprite.svg#html5`. See [example](https://github.com/kisenka/svg-sprite-loader/blob/master/examples/extract-sprite/build/main.css#L4). You should change [webpack.config.ts:25](https://github.com/thasmo/packman/blob/d1ae016e0f8ed3e006047d81d96c0c518da151fc/webpack.config.ts#L25) to always be `true`.
2. svg-sprite-loader in extract mode will not work with ExtractTextWebpackPlugin with `allChunks: true`. If you set `allChunks: false` in [corresponding config section](https://github.com/thasmo/packman/blob/d1ae016e0f8ed3e006047d81d96c0c518da151fc/.packman/packs/compilation-sass.ts#L33) loader works as expected. This should be mentioned in readme, I'll do it later :)

**Comment by thasmo** [comment]
Hey! Thanks for your response.

I understand. So, when disabling `allChunks` it won't extract, in my case, all the CSS from the vendors chunk. I'm struggling to understand how I can do this with `allChunks` disabled. I know it's not in the scope of this issue but do you have an idea how I would still export all CSS with `allChunks` disabled?

**Comment by kisenka** [comment]
This is not possible at the moment, but I'll do some research.

**Comment by thasmo** [comment]
Just wanted to let you know that I tried [karify/external-svg-sprite-loader](https://github.com/karify/external-svg-sprite-loader) and it seems that `allChunks: true` works as expected, exporting SVGs from all chunks. Maybe it's source holds the secret to what needs to be done to support `allChunks`. Keep up the good work! :+1:

**Comment by kisenka** [comment]
@thasmo check `svg-sprite-loader@beta`, it [should fix](https://github.com/kisenka/svg-sprite-loader/blob/e712692aaf97b777d43c544d6e71772f96b80dd4/test/loader.test.js#L125) issue with `allChunks: true` extract-text-webpack-plugin.

**Comment by kisenka** [comment]
@thasmo ping

**Comment by thasmo** [comment]
@kisenka Thank for your work on this - it does seem to work when using `allChunks: true` now!
