### ISSUE TITLE
Err: Can't find the css sprite file

### ISSUE THREAD

**Issue by raymondoh** [kisenka/svg-sprite-loader#215]
**Do you want to request a feature, report a bug or ask a question?**

**What is the current behavior?**

**What is the expected behavior?**

**If the current behavior is a bug, please provide the steps to reproduce, at least part of webpack config with loader configuration and piece of your code.**
**The best way is to create repo with minimal setup to demonstrate a problem (package.json, webpack config and your code).**
**It you don't want to create a repository - create a [gist](http://gist.github.com) with multiple files**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please tell us about your environment:**

- Node.js version: ?
- webpack version: ?
- svg-sprite-loader version: ? 
- OS type & version: ?

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**
Hi. My issue is that sprite images are not being generated on the page resulting in a console error "file not found". I am using webpack 3, node v8.9.0, svg-sprite-loader v.3.4.1 and Mac OS 10.11.6. On my html page I can highlight the empty element and the corresponding css reads: 'background: url(icons-sprite.svg#twitter-usage)'. I have tried changing publicPath and outputPath but still no success. Can you give me any suggestions to try or here is the repo if you are kind enough to take a look: https://github.com/raymondoh/travel-site.git.
Thanks

**Comment by kisenka** [comment]
Unfortunately sprite-loader can't resolve resulting sprite filename according to resource which refers to it. That means if you store compiled stylesheets in `css` folder and sprite is placed in root folder stylesheet will refers to it in current folder (`css`). It can be fixed by adding `output.publicPath: '/'`. 
And second thing, you don't need `plainSprite: true` option, because it used in case when you download sprite on runtime via AJAX and inject it to DOM manually.
