### ISSUE TITLE
How to fix svg-sprite-loader exception?

### ISSUE THREAD

**Issue by Alcadur** [kisenka/svg-sprite-loader#237]
How to fix: `svg-sprite-loader exception. Some loaders will be applied after svg-sprite-loader in extract mode`

**Comment by kisenka** [comment]
Review your webpack config and check that svg-sprite-loader is the latest applied loader to SVGs.

**Comment by Alcadur** [comment]
Yes, You can close it

pon., 19.03.2018, 10:19 użytkownik Stas Kurilov <notifications@github.com>
napisał:

**Comment by pkarev** [comment]
I spent a whole bunch of time in order to fix this warning (i'm using symfony webpack encore).

The reason was that webpack encore has it's default file loader for all kind of image assets and it applies it always the last.

My solution is to add in your webpack config next code:

1.Disable default image loader in order to avoid svg-sprite-loader exception:   
`.disableImagesLoader()`

2.And then enable it again excluding the path with svg assets that i use for generate sprite in extract mode:   
```
.addRule({   
    test: /\.(png|jpg|jpeg|gif|ico|svg|webp)$/,   
    loader: 'file-loader',   
    exclude: [your_path_to_svg_assets],
    options: {
        name: 'images/[name].[hash:8].[ext]',
    }
})
```
Hope, this will save time to somebody.

**Comment by matthewmcclatchie** [comment]
Sorry to bring this one back up, but I'm having the very same Warning in my console. 

`svg-sprite-loader exception. Some loaders will be applied after svg-sprite-loader in extract mode`

I'm using [Razzle](https://github.com/jaredpalmer/razzle) to generate a site so am extending the default Webpack config by following the instructions [here](https://github.com/jaredpalmer/razzle#extending-webpack).

I'm using the extract configuration to produce a file that ends up in the `/public` directory. 

Everything is working well, but I'm seeing a Warning in my console for each SVG in my 'raw' directory.
