### ISSUE TITLE
Can you extract AND inline the same svg?

### ISSUE THREAD

**Issue by gswirrl** [kisenka/svg-sprite-loader#285]
Is is possible *both* to extract svg to a file *AND* inject the same svg into a server-side rendered page?

Im using a setup similar to https://github.com/kisenka/svg-sprite-loader/tree/master/examples/server-side-rendering. This works fine without extract enabled.

Enabling extract mode successfully generates the sprite file, but now an empty sprite is output into the html:

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                    style="position: absolute; width: 0; height: 0" id="__SVG_SPRITE_NODE__"></svg>
```

Very grateful for your advice

**Comment by kisenka** [comment]
If you're rendering sprite at server why do you need it as separate file? Extract sprite to a file needed by frontend code only.

**Comment by gswirrl** [comment]
> If you're rendering sprite at server why do you need it as separate file? Extract sprite to a file needed by frontend code only.

Some of the html in my app is generated at compile time, but some of it is generated on the fly. I need to bake the svg sprite into the static pages, but also re-use (inline) the same svg in the dynamic pages (which use a completely different stack).

Thanks for your help, and for the great loader.

**Comment by kisenka** [comment]
Unfortunately this is not possible in webpack, because you need to process the same file in different ways: in NodeJS env use isomorphic sprite; in browser env - use extracted sprite. To archive it you'll need to import the same SVGs in different ways, e.g.:

```js
// for browser env
import './img/image.svg?browser';

// for NodeJS
import './img/image.svg?server';
```

and webpack config:

```js
module: {
    rules: [
      {
        test: /\.svg\?browser/,
        loader: 'svg-sprite-loader',
        options: {
          extract: true
        }
      },
      {
        test: /\.svg\?server/,
        loader: 'svg-sprite-loader',
        options: {
          spriteModule: 'svg-sprite-loader/runtime/sprite.build'
        }
      }
    ]
  }
```

But, to be honest, it should be done via different loaders. Currently I am developing separate webpack plugin to extract sprites from SVGs. You can try it instead of extracting mode, but currently it has no documentation :) The package name is `extract-svg-sprite-webpack-plugin` and it configures like this:

```js
const SpritePlugin = require('extract-svg-sprite-webpack-plugin');

module.exports = {
  module: {
    rules: [
      {
        test: /\.svg\?browser/,
        use: SpritePlugin.extract()
      }
    ]
  },

  plugins: [
    new SpritePlugin({
      filename: 'sprite.svg',
      spriteType: 'stack'
    })
  ]
};
```

I am plan to release it officially during July and drop extract mode in svg-sprite-loader

**Comment by gswirrl** [comment]
Wow - ha - the double import idea is a genius hack! :-)

But you're definitely right too that multiple loaders is best. I'm about to give extract-svg-sprite-webpack-plugin a g - thank you for the advance notice.

Very grateful for your work. Thank you so much. Have a great day.

**Comment by MarmaladeKnight** [comment]
I have the same issue but the reason is that if I connect extracted sprite via url in xlink:href, I will miss the gradients. That`s why I want to connect sprite into the page without using link in icons
